# What is Equivalence Class partitioning method of testing? Generate the test cases for a
# program which finds the largest among three numbers A, B, C. Given the range of A [1, 50],
# B[1,100], C[1, 25].

# Answer: Equivalence class partitioning is a method of testing in which the input domain is
# divided into a number of classes, each of which is tested separately. The test cases are
# generated by selecting one value from each class. 

# Test cases for the program using equivalent class partitioning which finds the largest among three numbers A, B, C. Given the
# range of A [1, 50], B[1,100], C[1, 25].

# Test case 1: A = 1, B = 1, C = 1
# Test case 2: A = 1, B = 1, C = 25
# Test case 3: A = 1, B = 1, C = 50
# Test case 4: A = 1, B = 25, C = 1
# Test case 5: A = 1, B = 25, C = 25
# Test case 6: A = 1, B = 25, C = 50
# Test case 7: A = 1, B = 50, C = 1
# Test case 8: A = 1, B = 50, C = 25
# Test case 9: A = 1, B = 50, C = 50
# Test case 10: A = 25, B = 1, C = 1
# Test case 11: A = 25, B = 1, C = 25
# Test case 12: A = 25, B = 1, C = 50
# Test case 13: A = 25, B = 25, C = 1
# Test case 14: A = 25, B = 25, C = 25
# Test case 15: A = 25, B = 25, C = 50
# Test case 16: A = 25, B = 50, C = 1
# Test case 17: A = 25, B = 50, C = 25
# Test case 18: A = 25, B = 50, C = 50
# Test case 19: A = 50, B = 1, C = 1
# Test case 20: A = 50, B = 1, C = 25
# Test case 21: A = 50, B = 1, C = 50
# Test case 22: A = 50, B = 25, C = 1
# Test case 23: A = 50, B = 25, C = 25
# Test case 24: A = 50, B = 25, C = 50
# Test case 25: A = 50, B = 50, C = 1
# Test case 26: A = 50, B = 50, C = 25
# Test case 27: A = 50, B = 50, C = 50
